---
title: 'STAT 636: Final Project'
author: "Katie Hill, Asmita Nagila, Jerrin Wiley"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
```

## Project Data Source

<https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success>

Instances: 4424

Features: 36

Goal: Classify Students into 3 categories: Dropout, Enrolled, and Graduate

## Data Import

Import Data

```{r}
data <- read.csv("data.csv",sep=";")
attach(data)
```

```{r}
head(data)
```

Check for Missing Values

```{r}
which(is.na(data))
```

No line is missing data

## Data Exploration

```{r}
ggplot(data=data)+geom_bar(mapping=aes(x=Target))
```

## 

Build function to graph distribution of feature by target

```{r}
FeatureVsTarget = function(feature,name){
  print(ggplot(data=data)+
          geom_boxplot(mapping=aes(x=reorder(Target,feature,FUN=median),y=feature))+xlab("Target")+ylab(name))
}
```

```{r}
FeatureVsTarget(Admission.grade)
```

Plot Features

```{r}
data_col <- colnames(data)
for(i in 1:ncol(data)){
  FeatureVsTarget(data[,i], data_col[i])
}

```
